/** @format */
// 'use client';

import type { Metadata } from 'next';
// import localFont from 'next/font/local';
import './globals.css';
import { lusitana, outfit } from '@/ui/fonts';
import Navbar from '@/components/custom/Navbar';
import { ThemeProvider } from 'next-themes';
import { TooltipProvider } from '@/components/ui/tooltip';
import Script from 'next/script';
import AdSense from '@/components/custom/AdSense';
import { Analytics } from '@vercel/analytics/react';
import MobileHeader from '@/components/custom/MobileHeader';
// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

export const metadata: Metadata = {
  metadataBase: new URL('https://www.codewithtabish.com/'),
  title: {
    default: 'Talha Tabish | Full Stack Developer',
    template: `%s | Tabish - Full Stack Developer`,
  },
  description:
    "Hi, I'm Tabish 👋 Full Stack Developer | Android & React Native Developer | Data Engineer | Adaptable Problem Solver.",
  keywords: [
    'Talha Tabish',
    'Tabish',
    'Full Stack Developer',
    'Android Developer',
    'React Native Developer',
    'Web Development',
    'Backend Development',
    'Frontend Development',
    'Data Engineer',
    'Software Engineer',
    'Programming',
    'Technology',
    'Portfolio',
    'Code With Tabish',
    'Code With Talha',
    'Talha Naeem',
    'Talha Tabish Developer',
    'Talha Naeem Developer',
    'JavaScript Developer',
    'Python Developer',
    'Kotlin Developer',
    'Java Developer',
    'Swift Developer',
    'Node.js Developer',
    'React Developer',
    'Vue.js Developer',
    'Angular Developer',
    'Next.js Developer',
    'MERN Stack Developer',
    'MEAN Stack Developer',
    'Frontend Developer Jobs',
    'Backend Developer Jobs',
    'Remote Full Stack Developer',
    'Freelance Developer',
    'Firebase Developer',
    'MongoDB Developer',
    'AWS Developer',
    'Google Cloud Developer',
    'Azure Developer',
    'Docker Developer',
    'CI/CD Developer',
    'DevOps Engineer',
    'Web App Development',
    'Mobile App Development',
    'App Developer',
    'Mobile Developer',
    'Cross-Platform Developer',
    'iOS Developer',
    'Android Studio Developer',
    'Xcode Developer',
    'Jetpack Compose Developer',
    'Responsive Web Design',
    'Progressive Web App Developer',
    'Single Page Application Developer',
    'Frontend Architecture',
    'UI/UX Design',
    'User Experience Developer',
    'Interactive Web Developer',
    'REST API Developer',
    'GraphQL Developer',
    'Serverless Architect',
    'Cloud Engineer',
    'Kubernetes Engineer',
    'Microservices Architect',
    'API Development',
    'Web API Developer',
    'React Hooks Developer',
    'State Management Developer',
    'Agile Developer',
    'Scrum Developer',
    'JavaScript Frameworks',
    'Web Assembly Developer',
    'Blockchain Developer',
    'Crypto Developer',
    'Ethereum Developer',
    'Solidity Developer',
    'Smart Contracts Developer',
    'Machine Learning Engineer',
    'AI Developer',
    'Data Scientist',
    'Big Data Engineer',
    'Hadoop Developer',
    'Spark Developer',
    'ETL Developer',
    'Business Intelligence Developer',
    'API Integrations Developer',
    'Database Administrator',
    'PostgreSQL Developer',
    'MySQL Developer',
    'SQLite Developer',
    'NoSQL Developer',
    'Redis Developer',
    'ElasticSearch Developer',
    'Data Structures Developer',
    'Algorithm Developer',
    'C++ Developer',
    'C# Developer',
    'Golang Developer',
    'Rust Developer',
    'PHP Developer',
    'Laravel Developer',
    'Symfony Developer',
    'Django Developer',
    'Flask Developer',
    'Spring Boot Developer',
    'Microservices Developer',
    'Event-Driven Architecture',
    'Messaging Queues Developer',
    'RabbitMQ Developer',
    'Kafka Developer',
    'Realtime Applications Developer',
    'Push Notifications Developer',
    'React Native Expert',
    'Flutter Developer',
    'Mobile App Architect',
    'Progressive Web App Expert',
    'App Optimization Specialist',
    'Serverless Developer',
    'API Gateway Developer',
    'Lambda Developer',
    'Cloud Functions Developer',
    'App Deployment Expert',
    'CI/CD Automation Engineer',
    'Full Stack Solutions',
    'Backend Solutions',
    'Web Development Solutions',
    'Mobile App Development Solutions',
    'Cloud Development Solutions',
    'Scalable Web Apps',
    'High Availability Architect',
    'Database Optimization',
    'Database Engineer',
    'Full Stack App Developer',
    'Professional Developer Portfolio',
    'Web App Expert',
    'Mobile App Programming',
    'Cross-Platform Expert',
    'Responsive Design',
    'Web Optimization Expert',
    'Speed Optimization Expert',
    'SEO Expert',
    'Web Performance Expert',
    'Content Management Systems',
    'CMS Developer',
    'WordPress Developer',
    'WooCommerce Developer',
    'Shopify Developer',
    'E-commerce Developer',
    'Payment Gateway Integration',
    'Stripe Developer',
    'PayPal Integration',
    'Online Store Developer',
    'Booking System Developer',
    'CRM System Developer',
    'ERP Developer',
    'Custom Software Solutions',
    'Enterprise Applications Developer',
    'Software Architect',
    'Lead Developer',
    'Development Team Lead',
    'Tech Lead',
    'Agile Software Development',
    'Scrum Master',
    'Digital Transformation Expert',
    'Automation Engineer',
    'Robotic Process Automation Developer',
    'CI/CD Pipelines Expert',
    'Cloud Computing Developer',
    'AWS Lambda Developer',
    'Azure Functions Developer',
    'Google Cloud Functions Developer',
    'Serverless Architect Expert',
    'Cloud-Native Developer',
    'Hybrid Cloud Architect',
    'Multi-Cloud Developer',
    'Infrastructure as Code Developer',
    'Terraform Developer',
    'CloudFormation Developer',
    'Ansible Developer',
    'Puppet Developer',
    'Jenkins Developer',
    'CI/CD Pipelines Automation',
    'Test Automation Developer',
    'Quality Assurance Engineer',
    'Load Testing Expert',
    'Unit Testing Developer',
    'Jest Developer',
    'Mocha Developer',
    'Chai Developer',
    'TDD Developer',
    'BDD Developer',
    'Software Development Life Cycle',
    'SDLC Expert',
    'Version Control Expert',
    'Git Developer',
    'GitHub Expert',
    'GitLab Expert',
    'Bitbucket Expert',
    'Code Collaboration',
    'Peer Code Review',
    'Code Quality Assurance',
    'Continuous Integration',
    'Continuous Delivery',
    'Agile Development Expert',
    'Scrum Developer Expert',
    'SaaS Developer',
    'Enterprise Software Developer',
    'Multi-Tenant Architect',
    'Business Applications Developer',
    'Startup Developer',
    'Scalable Solutions Architect',
    'Cloud Native Solutions',
    'DevOps Solutions Architect',
    'Automation Architect',
    'Software Engineering Expert',
    'System Design Expert',
    'Solution Architect',
    'API Architect',
    'Database Architect',
    'Data Flow Architect',
    'Backend Developer Solutions',
    'Frontend Developer Solutions',
    'Cross-Platform App Solutions',
    'Mobile App Optimization Expert',
    'AI Solutions Architect',
    'Machine Learning Solutions',
    'Data Engineering Architect',
    'Full Stack Developer Jobs',
    'Remote Developer Jobs',
    'Freelance Developer Jobs',
    'React Native Jobs',
    'Node.js Jobs',
    'Web Developer Jobs',
    'Software Engineer Jobs',
    'AI Developer Jobs',
    'Blockchain Developer Jobs',
    'App Developer Jobs',
    'Mobile Developer Jobs',
    'Full Stack Engineer Jobs',
    'Android Studio Expert',
    'Kotlin Expert',
    'Flutter Expert',
    'JavaScript Programming',
    'App Programming',
    'Cloud Expert',
    'Backend Developer Expert',
    'Frontend Developer Expert',
    'React Expert',
    'Code With Talha Naeem',
    'Tech With Talha',
    'Professional Portfolio',
    'Custom App Solutions',
    'Code With Talha Tabish',
    'Freelance Developer',
    'Tech Blog by Talha',
    'GitHub Portfolio',
    'Talha Tabish GitHub',
    'Talha Naeem GitHub',
    'Web Solutions Architect',
    'Professional Developer Profile',
    'Tech Innovations',
    'App Store Developer',
    'Play Store Developer',
    'App Store Optimization',
    'Website Optimization',
    'SEO Developer',
    'Website Speed Optimization',
    'Full Stack Web Development',
    'Talha Tabish Developer Expert',
    'Talha Naeem Developer Expert',
    'Talha Tabish Web Developer',
    'Talha Naeem Web Developer',
    'Talha Tabish Full Stack Solutions',
    'Talha Naeem Full Stack Solutions',
    'Talha Tabish Software Solutions',
    'Talha Naeem Software Solutions',
    'Talha Tabish Mobile App Developer',
    'Talha Naeem Mobile App Developer',
    'Talha Tabish Programming Expert',
    'Talha Naeem Programming Expert',
    'Talha Tabish Professional Developer',
    'Talha Naeem Professional Developer',
    'Talha Tabish Cloud Developer',
    'Talha Naeem Cloud Developer',
    'Talha Tabish React Developer',
    'Talha Naeem React Developer',
    'Talha Tabish JavaScript Developer',
    'Talha Naeem JavaScript Developer',
    'Talha Tabish Python Developer',
    'Talha Naeem Python Developer',
    'Talha Tabish Node.js Developer',
    'Talha Naeem Node.js Developer',
    'Talha Tabish Firebase Developer',
    'Talha Naeem Firebase Developer',
    'Talha Tabish Mobile Developer Solutions',
    'Talha Naeem Mobile Developer Solutions',
    'Talha Tabish Software Engineer',
    'Talha Naeem Software Engineer',
    'Talha Tabish Cloud Solutions Architect',
    'Talha Naeem Cloud Solutions Architect',
  ],

  openGraph: {
    title: 'Talha Tabish | Full Stack Developer',
    description:
      'I am a dedicated software engineer specializing in Android development, React Native, backend, and web development. Passionate about creating efficient, user-centric solutions.',
    url: 'https://www.codewithtabish.com/',
    siteName: 'Talha Tabish Portfolio',
    images: [
      {
        url: 'https://res-console.cloudinary.com/dnrt7rxxb/thumbnails/v1/image/upload/v1729274068/YTk4ZGE5NThlMzQwNDEwNWE4MDU0NTVkYmI5NzJmMWZfZGJibnhs/grid_landscape', // Portfolio's Open Graph image
        width: 1200,
        height: 630,
        alt: 'Talha Tabish Portfolio',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  twitter: {
    title: 'Talha Tabish | Full Stack Developer',
    card: 'summary_large_image',
    images: [
      'https://res-console.cloudinary.com/dnrt7rxxb/thumbnails/v1/image/upload/v1729274068/YTk4ZGE5NThlMzQwNDEwNWE4MDU0NTVkYmI5NzJmMWZfZGJibnhs/grid_landscape',
    ], // Twitter-specific image
  },
  verification: {
    google: '', // Add your Google verification code
    yandex: '', // Add your Yandex verification code
  },
  icons: {
    icon: 'https://res-console.cloudinary.com/dnrt7rxxb/thumbnails/v1/image/upload/v1729274068/YTk4ZGE5NThlMzQwNDEwNWE4MDU0NTVkYmI5NzJmMWZfZGJibnhs/grid_landscape', // Your favicon
    apple: '/apple-touch-icon.png', // Apple Touch Icon for iOS devices
    other: [
      { rel: 'manifest', url: '/site.webmanifest' }, // Manifest for web apps
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta
          name='google-adsense-account'
          content='ca-pub-5517689121320829'
        />

        <AdSense pId='pub-5517689121320829' />
      </head>
      {/* 5517689121320829 ' */}
      <body className={`${lusitana.className} antialiased`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='light'
        >
          <TooltipProvider delayDuration={0}>
            <MobileHeader />
            {children}
            <Navbar />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
